nugraph/pynuml

README.md, numl/core/out.py
Without this PR, I got the following 5 graphs with shape [2, 0]
and thus the program failed. This PR disables chunking for those
datasets with zero elements.
```
r7004_sr1311_evt65598 / edge_index_3d_u  shape= torch.Size([2, 0])
r7006_sr285_evt14273  / edge_index_3d_u  shape= torch.Size([2, 0])
r7049_sr1079_evt53995 / edge_index_3d_u  shape= torch.Size([2, 0])
r7001_sr451_evt22595  / edge_index_3d_v  shape= torch.Size([2, 0])
r7023_sr1870_evt93510 / edge_index_3d_u  shape= torch.Size([2, 0])
```
=> disable chunking/compression for empty datasets

example/process.py, numl/core/file.py, numl/core/out.py, numl/process/hitgraph.py, numl/process/vis.ipynb
* First cut the amount of boundary event into two halves based on the
average event amount boundary line.
* The first half is used to consider assigning the boundary event to
process i and the second half process i+1
* The boundary event will be assigned to the process i or i+1 whoever
has the bigger half.
* Add command-line option -d to use event ID based data partitioning.
The default is to use event number based partitioning, i.e. numbers
of rows per event.
* Fix when some processes have no event ID assigned
* add timers for file open and data partition calculation
=> Use a better event assignment method suggested by @jrexliao

pynuml/io/out.py
Without this fix, the following error messages will appear when running `example/process.py`.
```
Traceback (most recent call last):
File "example/process.py", line 60, in <module>
main(sys.argv[1:])
File "example/process.py", line 53, in main
pynuml.process.hitgraph.process_file(out, inputfile,
File "pynuml/process/hitgraph.py", line 259, in process_file
out.save(data, name)
File "pynuml/io/out.py", line 79, in save
ctype = np.dtype(fields)
TypeError: Cannot interpret 'torch.int64' as a data type
```
=> bug fix: convert zero-sized tensor to numpy array

pynuml/process/hitgraph.py
Avoid using hard-coded number for the number of timers.
Mismatched numpy array size can cause unexpected results from MPI gather.
=> bug fix: number of timers

pynuml/io/file.py
Note h5py File.get() may return None when the requested dataset does not exist, which is not an exception.
=> bug fix: properly throw exception when seq/seq_cnt does not exit

pynuml/io/file.py
This PR is to fulfill #23.
The default partitioning key dataset is set to `/event_table/event_id`
Below is an example of usage of function call `pynuml.io.File()`.
```python
#!/usr/bin/env python
import argparse
import pynuml
def configure():
args = argparse.ArgumentParser()
args.add_argument("-i", "--infile", type=str, required=True,
help="input HDF5 file")
args.add_argument("-o", "--outfile", type=str, required=True,
help="output file name")
args.add_argument("-k", "--parKey", type=str, required=False,
help="partitioing key dataset name")
return args.parse_args()  
def process(args):
if args.parKey == None:
f = pynuml.io.File(args.infile)
else:
f = pynuml.io.File(args.infile, args.parKey)
processor = pynuml.process.HitGraphProducer(
file=f,
labeller=pynuml.labels.standard)
out = …
```
=> Add an optional argument for partitioning key dataset name

pynuml/io/h5interface.py, pynuml/process/hitgraph.py
this PR fixes a bug that occurs when loading event truth labels from the heterogeneous graph compound data object. the previous implementation manually defined the names of graph attributes that corresponded to scalar values:
https://github.com/vhewes/pynuml/blob/09cad6d0ae01f3094139bcec6e218e6cbc9d56ca/pynuml/io/h5interface.py#L77-L78
since the event truth is a tensor containing a single value, it counts as a scalar value – but since it wasn't present in this list, it was erroneously being read as an empty multidimensional tensor.
the new implementation simply queries the size of the dataset to check whether it's a scalar value:
https://github.com/vhewes/pynuml/blob/1a4530b54f0ae31ef36fdfa6e624b56d31cd9aa9/pynuml/io/h5interface.py#L77-L78
which should be much more flexible and robust. …
=> Improve handling of scalar values in HDF5 compound data loading

docs/conf.py, pynuml/__init__.py, pynuml/io/h5interface.py
this PR fixes an issue with handling scalar values and empty tensors in `H5Interface`. there was a previous PR to fix this issue that didn't work as intended, but this PR has been tested and appears to fix the issue. essentially, it's difficult to disambiguate between empty tensors and scalar values when loading tensors from the graph compound data object, and writing logic to do so is non-trivial.
the previous logic utilised a list of special keys corresponding to scalar values, and would load those as scalars; anything else would be loaded as an empty edge index tensor. however, this was problematic for two reasons:
- adding any new scalar values (such as an event truth label, which is how this issue was encountered) will cause problems if the corresponding keys weren't added to …
=> Fix bug in compound data object

pynuml/labels/flavor.py, pynuml/process/hitgraph.py
this PR adds 2D and 3D event vertex position ground truth labels to graph processing, which enables the development of vertex regression tasks. the implementation is pretty inflexible for now, and will only work with MicroBooNE open data release files for the time being, but this should pave the way for future development on the HDF5-making side that will enable more widespread use.
this functionality is disabled by default, and must be manually enabled, so applications other than the uboone open data release should be unaffected.
also included is a *very* minor fix to event label processing: the event labelling was previously included inside the loop over detector planes, meaning it was run multiple times, which is totally harmless but unnecessary. as part of this PR, the event labelling …
=> add vertex labels to graph object

pynuml/plot/graph.py
this PR includes bug fixes and implementation changes in pynuml's graph plotting utility.
PR #39 included changes to the names of ground truth tensors in the graph object, and also changes to how the various truth tensors are stored. the `GraphPlot` utility was never updated to reflect these changes, which caused errors when it was run. this PR updates `GraphPlot` so that it's compatible with the new graph structure.
`GraphPlot` has also been modified conceptually. previously, its `plot` function would take in a data object, some plotting options, an output file stub and some options for output filetypes (ie. PNG, HTML). however, this turns out to be pretty inflexible for cases where the user wants to visualise the plot in a notebook environment instead of writing it to disk, so the …
=> update graph plotting

scripts/install_ph5concat_conda.sh
add a simple utility script that installs the merging and metadata sequencing binaries to a conda environment from the [ph5concat repository](https://github.com/NU-CUCIS/ph5concat).
=> add script for installing ph5concat

pynuml/process/hitgraph.py
previously, the truth label tensor for the 3D vertex coordinates was a single-dimension tensor with size 3, which caused issues when batching together multiple graphs. this reshapes each event's true vertex to a two-dimensional tensor with size (1, 3), so batching N graphs together produces a tensor with size (N, 3), which is what we want.
=> add second dimension to 3D vertex truth

pynuml/labels/standard.py
Tyler S came across an instance of a charged tau lepton showing up in an atmospheric event, so i'm adding it to the labelling scheme here. for now i'm calling it HIP, but we should probably revisit that down the road
=> label charged tau as HIP

pynuml/process/hitgraph.py
only fetch the event table during graph processing if it's initialised, which will occur if we're labelling either the event or the vertex
=> safeguard event table access

pynuml/labels/__init__.py, pynuml/labels/pdk.py
this adds an alternative to standard neutrino flavour event labelling, and replaces it with a binary score labelling events with 0 if they're from a neutrino ancestor and 1 otherwise. when working with nucleon decay physics, this should be equivalent to 0 = atmospheric neutrino, 1 = nucleon decay.
=> add proton decay event labelling

pynuml/__init__.py
from now on, i'll tag numbered versions for the release only going forward, while the version in main will use a '.dev' patch version
=> update to dev version

pynuml/labels/standard.py
give it the kaon label because it's a heavy meson
=> add D meson labelling

.gitignore, README.md, docs/install/installation.rst
the documentation on installing dependencies instructs users to install Mambaforge, but then uses `conda` commands in the docs. if the users of these instructions are using Mambaforge, then they should use the (better) `mamba` interface instead – this PR updates the documentation accordingly.
=> update documentation to use mamba command

pynuml/plot/graph.py
a few tweaks to graph plotting:
previously, the code would just use plotly's default red and blue colours, but the mapping of those colours to signal and background were inconsistent. the code has been reworked to use coral for background and sea green for signal :)
a couple of tweaks here:
since we have no true semantic labels for background hits, those graph nodes would just get removed from event displays entirely when plotting true semantic labels, regardless of what the user passed for the `filter` argument in the plotting function. i tweaked the code to add an extra `background` category for sematic labels, so those hits are now shown greyed out. if the user doesn't want them, they can simply pass `filter=true` to recover the old behaviour
the network generates a semantic prediction …
=> Update graph plotting utilities

pynuml/process/hitgraph.py
this is a hotfix for a pathology in the uboone open dataset. we should fix this upstream in the long run, but this will filter out the event in question from the processed graphs in the short term.
=> check for integral outliers

pynuml/plot/graph.py, pynuml/process/hitgraph.py, tests/test_process.py
- Remove unused data hit filtering option, as it is handled by the filter decoder.
- Add an option to store detailed truth information inside the processed graph object.
- Add an option to store a true 3D position for each detector hit.
- Visualize detailed truth information when hovering over hit, if present.
- Improve visualization of instance labels.
- Add option to visualize hits as 3D point cloud, if present.
- Set legend to default to horizontal.
- Added function to test processing with uboone open data release.
=> Updates to graph processing and plotting

pynuml/labels/standard.py
remove delta ray label; any hits belonging to delta rays are labelled according to the particle that produced them. this change was already implemented in the NuGraph3 dataset, and is now becoming standard.
=> remove delta ray from standard labelling

README.md, docs/index.rst, docs/install/installation.rst, pynuml/__init__.py, pyproject.toml
update to newest release version
=> bump to v24.6.dev0

pynuml/labels/standard.py
the condition that any electrons or positrons ending in the "eIoni" process be labelled as diffuse should go _after_ the piece of the code that identifies delta rays
=> fix bug when labelling delta rays
