example/process.py
numl/core/out.py
numl/process/hitgraph.py

Option '-f' allows to overwrite the output files, if already exist.

Add command-line option '-f'

---

numl/process/hitgraph.py

This should provide a better report on what labelling method is used.
Same for edge indexing method used.

Report the kind of labelling and edge indexing used

---

numl/process/hitgraph.py

Set the default lower bound to 20, the value currently used.

Add argument lower_bnd, the lower bound number of hits

---

example/process.py
numl/core/file.py
numl/process/hitgraph.py
numl/process/vis.ipynb

For parallel file read (e.g. hitgraph.py), one should now call function NuMLFile.read_data_all().
For sequential file read (e.g. visualization.py), one should call function NuMLFile.read_data().

Separate sequential file read from parallel read

---

pynuml/io/file.py

pull in Giuseppe's recent bug fixes

bug fixes in File class

---

example/process.py
pynuml/io/file.py

update processing example script to reflect changes in packages structure, and also make the `add_group` function in the `File` class smarter, so it can recognise groups and keys that have already been added and know not to duplicate them

update file interface

---

pynuml/io/file.py

* To check if a list is empty, use 
```
if not list_obj:
```
instead of
```
if not len(list_obj):
```
* move the print statement for lower and upper after their are set
* check if ecent_table/event_id exists
* check if shape[0] of all datasets in the same group are the same
* check if datasets in keys are available in the input file

A few minor fixes

---

pynuml/io/file.py
pynuml/io/h5interface.py
pynuml/io/out.py
pynuml/labels/standard.py
pynuml/util.py

Some functions in the code had a `NoReturn` type which is usually used to signal that the function will never return. Instead a `None` return type is usually used when a function has no return value. Closes #27

Fix return types

---

LICENSE
pynuml/__init__.py
pynuml/process/hitgraph.py
pyproject.toml

updated to new package version. previous version was broken when importing from pypi; i switched to `flit` as an engine for publishing and it seems to be working very nicely

version 23.5.1

---

pynuml/io/file.py
pynuml/io/out.py
pynuml/process/hitgraph.py

two major updates here:
- fix a bug in metadata processing that slipped through into main
- update "np.int" -> "int" since numpy int was recently deprecated

merge in development branch

---

pynuml/__init__.py

incrementing version number for new release

update to version 23.5.2

---

pynuml/labels/standard.py

add in new particle types and physics processes to resolve #29

update standard labelling

---

pynuml/labels/__init__.py
pynuml/labels/flavor.py
pynuml/process/hitgraph.py

add simple event labelling, so we can test the event classification head with the uboone open dataset

add event labelling

---

pynuml/__init__.py

cut version 23.6.0

---

docs/conf.py
pynuml/__init__.py

update to version 23.7.0

---

pynuml/labels/flavor.py

Or we can do it in another way -- copy the modified `FlavorLabels` class to `process.py` and override it based on one's needs.

add nutau label for FlavorLabels class

---

pynuml/plot/graph.py

mostly small quality-of-life updates to graph plotting utility:
- use shared y axis across planes
- add check against casting full batch to dataframe
- add event metadata to dataframe
- allow the user to configure the size of the canvas

updates to plotting

---

pynuml/process/hitgraph.py

use the corrected version of the true 3D vertex position as ground truth

switch to nu_vtx_corr

---

meta.yaml

this allows us to build conda packages and publish pynuml on the `numl` channel :)

add metadata file for conda package

---

pynuml/io/file.py

this adds a simple `__str__` function to the `Event` class, which allows the user to print out the dataframes and keys included in a pynuml event object. this is useful for knowing how to index things while developing code.

add summary printout for Event class

---

pynuml/labels/standard.py

I think these events should be classified as diffuse similar to the other events in which are included in the or statement.

Add multiple scattering to the standard labeler

---

pynuml/process/hitgraph.py

PyG 2.4 changes how transforms work, such that the data object is no longer modified in-place. this PR updates our processing code to be compatible with the new version, without breaking compatibility with older versions.

fix Delaunay edge processing

---

pynuml/__init__.py
pynuml/meta.yaml

bump the development version number and update conda recipe

bump to v23.11.dev

---

.gitignore
pynuml/plot/graph.py
tests/test_process.py

Fixed a bug where 3D hit position is expected by the plotting code, even if it isn't being used. Also added plotting to unit test and added a couple of small things to gitignore.

Bug fixes in graph plotting code

---

pynuml/process/hitgraph.py
tests/test_process.py

Noticed and fixed some logic errors in graph processing for the new 3D hit position truth. Also added a unit test for processing on a temporary DUNE nutau test file; the input file should be updated once the full dataset is available.

Fix 3D truth formation

---

tests/test_process.py

update path to test file on Heimdall

update dune testfile location

---

.github/workflows/pypi.yml

add a github action yaml to automatically publish to PyPi every time a release is created

github action for pypi release

---

pynuml/process/hitgraph.py

add reconstructed 3D coordinates from spacepoints to graph data, so they can be used to aid prediction of the vertex position.

add true nexus position

---

pynuml/plot/graph.py

add in code to plot predicted and materialized instances

plot predicted instances

---

pynuml/io/file.py

A quick update to try generating graphs one event at a time,
in case out-of-memory errors are encountered.

Fix bug: null events at the beginning and add option to process one event at a time
